apiVersion: v1
kind: Service
metadata:
  name: $IMAGE_REPO_NAME
spec:
  selector:
    app: $IMAGE_REPO_NAME
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
    - protocol: TCP
      port: 7071
      targetPort: 7071
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8081
      targetPort: 8081
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
