apiVersion: v1
kind: Service
metadata:
  name: $IMAGE_REPO_NAME
spec:
  selector:
    app: $IMAGE_REPO_NAME
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
